rk3110\_hw1
================
Rose Killian
1/22/2022

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.4     v dplyr   1.0.7
    ## v tidyr   1.1.3     v stringr 1.4.0
    ## v readr   2.0.1     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Read in .csv

``` r
hw1_df = 
  read_csv("data/bcdata_Assignment1.csv") %>% 
    janitor::clean_names()
```

    ## Rows: 116 Columns: 10

    ## -- Column specification --------------------------------------------------------
    ## Delimiter: ","
    ## dbl (10): Age, BMI, Glucose, Insulin, HOMA, Leptin, Adiponectin, Resistin, M...

    ## 
    ## i Use `spec()` to retrieve the full column specification for this data.
    ## i Specify the column types or set `show_col_types = FALSE` to quiet this message.

# Question 1

Table of quantitative features

``` r
hw1_df %>% 
  select(age:mcp_1) %>% 
  summary() %>% 
  knitr::kable()
```

|     | age          | bmi           | glucose        | insulin        | homa            | leptin         | adiponectin    | resistin       | mcp\_1          |
|:----|:-------------|:--------------|:---------------|:---------------|:----------------|:---------------|:---------------|:---------------|:----------------|
|     | Min. :24.0   | Min. :18.37   | Min. : 60.00   | Min. : 2.432   | Min. : 0.4674   | Min. : 4.311   | Min. : 1.656   | Min. : 3.210   | Min. : 45.84    |
|     | 1st Qu.:45.0 | 1st Qu.:22.97 | 1st Qu.: 85.75 | 1st Qu.: 4.359 | 1st Qu.: 0.9180 | 1st Qu.:12.314 | 1st Qu.: 5.474 | 1st Qu.: 6.882 | 1st Qu.: 269.98 |
|     | Median :56.0 | Median :27.66 | Median : 92.00 | Median : 5.925 | Median : 1.3809 | Median :20.271 | Median : 8.353 | Median :10.828 | Median : 471.32 |
|     | Mean :57.3   | Mean :27.58   | Mean : 97.79   | Mean :10.012   | Mean : 2.6950   | Mean :26.615   | Mean :10.181   | Mean :14.726   | Mean : 534.65   |
|     | 3rd Qu.:71.0 | 3rd Qu.:31.24 | 3rd Qu.:102.00 | 3rd Qu.:11.189 | 3rd Qu.: 2.8578 | 3rd Qu.:37.378 | 3rd Qu.:11.816 | 3rd Qu.:17.755 | 3rd Qu.: 700.09 |
|     | Max. :89.0   | Max. :38.58   | Max. :201.00   | Max. :58.460   | Max. :25.0503   | Max. :90.280   | Max. :38.040   | Max. :82.100   | Max. :1698.44   |

# Question 2

Recode BMI

``` r
q2_df = 
  hw1_df %>% 
  mutate(
    bmi_cat = as_factor(case_when(
      bmi < 16.5 ~ "severely underweight",
      bmi < 18.5 ~ "underweight",
      bmi >= 18.5 & bmi <= 24.9 ~ "normal weight",
      bmi >= 25 & bmi <= 29.9 ~ "overweight",
      bmi >= 30 & bmi <= 34.9 ~ "obesity class I",
      bmi >= 35 & bmi <= 39.9 ~ "obesity class II",
      bmi >= 40 ~ "obesity class III"
    )
  ))

q2_df = 
  q2_df %>% 
  mutate(
    bmi_cat = 
      fct_relevel(bmi_cat,
                  "underweight",
                  "normal weight",
                  "overweight",
                  "obesity class I",
                  "obesity class II"))

#only 5 levels re-ordered as the sample does not contain observations for the lowest or highest BMI categories
```

# Question 3

Bar chart of proportion of breast cancer cases/controls within each BMI
category

``` r
q2_df %>% 
  ggplot(aes(x = bmi_cat)) +
  geom_bar(aes(fill = bmi_cat)) +
  facet_grid(. ~classification) +
  theme(axis.text.x = element_text(angle = 90), legend.position = "none")
```

<img src="p8451_hw1_rk3110_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />

# Question 4

Logistic regression

``` r
hw1_df = 
  hw1_df %>% 
  mutate(
    class = as.numeric(classification > 1)
  )

fit_logistic =
  glm(class ~ glucose + homa + leptin + bmi + age, data = hw1_df, family = binomial())

fit_logistic %>% 
  broom::tidy()
```

    ## # A tibble: 6 x 5
    ##   term        estimate std.error statistic  p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
    ## 1 (Intercept) -3.63       2.36      -1.54  0.124   
    ## 2 glucose      0.0817     0.0235     3.47  0.000515
    ## 3 homa         0.274      0.172      1.59  0.111   
    ## 4 leptin      -0.00857    0.0158    -0.543 0.587   
    ## 5 bmi         -0.104      0.0566    -1.84  0.0657  
    ## 6 age         -0.0229     0.0144    -1.59  0.111

``` r
confint(fit_logistic, level = 0.95)
```

    ## Waiting for profiling to be done...

    ##                   2.5 %      97.5 %
    ## (Intercept) -8.54138756 0.754487774
    ## glucose      0.03956613 0.132397841
    ## homa        -0.02555240 0.653222623
    ## leptin      -0.04019445 0.022416142
    ## bmi         -0.21944692 0.004398024
    ## age         -0.05192184 0.004856327

In order to interpret the beta and 95% confidence interval we must first
exponentiate them.

``` r
exp(cbind(OR = coef(fit_logistic), confint(fit_logistic, level = 0.95)))
```

    ## Waiting for profiling to be done...

    ##                     OR        2.5 %   97.5 %
    ## (Intercept) 0.02662074 0.0001952192 2.126522
    ## glucose     1.08512884 1.0403592957 1.141562
    ## homa        1.31505988 0.9747713042 1.921724
    ## leptin      0.99146285 0.9606026348 1.022669
    ## bmi         0.90099055 0.8029627758 1.004408
    ## age         0.97737883 0.9494030652 1.004868

On average, for every one-unit increase in HOMA-IR, the odds of breast
cancer increases by 1.32. We are 95% confident that the true change in
odds of breast cancer per unit increase in HOMA-IR is between 0.975 and
1.92.

# Question 5

Linear regression

``` r
fit = 
  lm(insulin ~ bmi + age + glucose, data = hw1_df)

fit %>% 
  broom::tidy()
```

    ## # A tibble: 4 x 5
    ##   term        estimate std.error statistic      p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>        <dbl>
    ## 1 (Intercept) -13.5       5.86      -2.30  0.0231      
    ## 2 bmi           0.150     0.164      0.914 0.363       
    ## 3 age          -0.0540    0.0519    -1.04  0.301       
    ## 4 glucose       0.230     0.0375     6.13  0.0000000137

``` r
confint(fit, level = 0.95)
```

    ##                   2.5 %      97.5 %
    ## (Intercept) -25.1054353 -1.88608318
    ## bmi          -0.1748942  0.47427491
    ## age          -0.1569321  0.04888876
    ## glucose       0.1554864  0.30414939

On average, for every one year increase in age, insulin increases by
0.230 units. We are 95% confident that the true increase in insulin for
every one year increase in age is between 0.155 and 0.304 units.
